### ISSUE TITLE
Server crashing with Iron Furnaces

### ISSUE THREAD

**Issue by originunseen** [Shadows-of-Fire/FastSuite#1]
Server crashed twice when using furnaces. Attached is one of the crash reports. The other is pretty much identical.

Expected Behavior is not to crash. 

Iron Furnaces Version 2.6.7 for Minecraft version 1.16.5. FastSuite version 1.0.0 for Minecraft version 1.16.5.

[crash-2021-04-29_16.59.57-server.txt](https://github.com/Shadows-of-Fire/FastSuite/files/6401976/crash-2021-04-29_16.59.57-server.txt)

**Comment by Gbergz** [comment]
I'll add this here, quick glance seems like an interaction with Polymorph
https://gist.github.com/Gbergz/a3772c2f2c07881d0f33b8c304eece1a

**Comment by Shadows-of-Fire** [comment]
I can't for the life of me see why that would be happening.  I just ran a stress test with about 500k recipes and it was unfazed.
However upon further inspection and some thinking there's not really a benefit to me overriding the getAllMatches as it always has to iterate the entire list anyway, so I'll just let it be vanilla.

**Comment by Shadows-of-Fire** [comment]
af52837193d88f9b71b827a2b56eaa5dcff608fe
