### ISSUE TITLE
Crash Caused by Fast Suite

### ISSUE THREAD

**Issue by CameoDaManeo** [Shadows-of-Fire/FastSuite#10]
I run a server and it's been crashing every time a particular player joins. The crash report had a bunch of stuff regarding Tinkers' Construct and Fast Suite. So I deleted Fast Suite and now it's not crashing anymore.

KnightMiner (dev for Tinkers') told me to report the issue here, as it's not the first instance of this happening that he's seen.

Here's a full server log.
[debug-2.log.gz](https://github.com/Shadows-of-Fire/FastSuite/files/6928305/debug-2.log.gz)

**Comment by CameoDaManeo** [comment]
Here's the crash report too!

[crash-2021-08-03_22.26.45-server.txt](https://github.com/Shadows-of-Fire/FastSuite/files/6928597/crash-2021-08-03_22.26.45-server.txt)

**Comment by Shadows-of-Fire** [comment]
Current suspicion is that some threadedness is breaking everything, though the stacktraces are unhelpful and nothing is conclusive.

**Comment by Shadows-of-Fire** [comment]
Can you see if this jar resolves the issue? https://github.com/Shadows-of-Fire/FastSuite/releases/tag/1.1.1
