### ISSUE TITLE
[Forge 1.18.1] Fast Suite has failed to load correctly

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Shadows-of-Fire/FastSuite#13]
_Forge version is 39.0.9. FS version is 3.0.0._
When I started up Minecraft, a startup error occurred regarding your mod.

Crash report: [crash-2021-12-28_12.02.03-fml.txt](https://github.com/Shadows-of-Fire/FastSuite/files/7784324/crash-2021-12-28_12.02.03-fml.txt)
Log: [latest.log](https://github.com/Shadows-of-Fire/FastSuite/files/7784335/latest.log)

![2021-12-28_12 06 05](https://user-images.githubusercontent.com/72312697/147560054-84f6a766-b20d-4a91-aa2a-63a49e85dd2d.png)

**Comment by Shadows-of-Fire** [comment]
It would appear you dont have placebo installed (and that's the issue)
I guess the dependency declaration is missing

**Comment by GeorgeOrwell1** [comment]
It seems to work now, thanks! I'll leave this issue open in case you want a reminder to add a dependency declaration.
