### ISSUE TITLE
Modded items Don't Smelt

### ISSUE THREAD

**Issue by AddAmazeing** [Shadows-of-Fire/FastSuite#15]
Elemental Craft "Pure Ores" don't smelt in Furnaces while Fast Suite is installed (1.16.5).

To recreate: have the shown mods ([Elemental Craft](https://www.curseforge.com/minecraft/mc-mods/elemental-craft/files), [DPAnvil](https://www.curseforge.com/minecraft/mc-mods/datapack-anvil/files), [Fast Suite](https://www.curseforge.com/minecraft/mc-mods/fastsuite/files/3419895), [Placebo](https://www.curseforge.com/minecraft/mc-mods/placebo/files/3437009) and [JEI](https://www.curseforge.com/minecraft/mc-mods/jei/files/3590083)) installed and put "Pure Iron Ore Chunks" in a Furnace with fuel.

Vanilla items as well as other modded items are able to smelt in Furnaces.

Demonstration with & without Fast Suite:
![With](https://user-images.githubusercontent.com/79289593/151685189-18f2ff98-5789-49b8-8632-0c51a4a7fa8b.png)
![Without](https://user-images.githubusercontent.com/79289593/151685190-707d0ffc-06d9-4366-8305-c2bf3c7441de.png)
:

**Comment by Shadows-of-Fire** [comment]
Interesting... Does that happen with just the two installed?

**Comment by Shadows-of-Fire** [comment]
Closing as 1.16.5 is no longer supported
