### ISSUE TITLE
Compatibility level JAVA_8 specified by fastsuite.mixins.json is lower than the default level supported by the current mixin service (JAVA_16).

### ISSUE THREAD

**Issue by SDUBZ** [Shadows-of-Fire/FastSuite#20]
Forge:1.18.2-40.1.82
Fastsuite: 3.0.2
this issue seems to be happening to many mods since forge 67+
https://gist.github.com/SDUBZ/a29863a5756a95cfa2b8861b21d8d656

**Comment by Shadows-of-Fire** [comment]
This is a debug level warning that does not cause any real issues.  I'd appreciate it not be spammed across all my trackers.
