### ISSUE TITLE
Bug with AE2 Wireless Crafting Terminal

### ISSUE THREAD

**Issue by TomasGnG** [Shadows-of-Fire/FastSuite#22]
Playing on a ATM8 1.0.8 server.

I crafted the Block Player by Industrial Foregoing and closed the inventory.
Afterwards the terminal was broken and I couldn't open it anymore nor my friend could.

FastSuite Version: 1.19.2-4.0.0
Error: https://mclo.gs/bwQGYRW

**Comment by Shadows-of-Fire** [comment]
You are unable to craft because the IE shader recipe is throwing an exception - this is not FS related
