### ISSUE TITLE
Crash while using RFTools scanner 

### ISSUE THREAD

**Issue by GooseterV** [Shadows-of-Fire/FastSuite#23]
[crash-2023-06-08_14.14.59-client.txt](https://github.com/Shadows-of-Fire/FastSuite/files/11691805/crash-2023-06-08_14.14.59-client.txt)
crash log attached above, modpack author told me to report here first
as title suggests i just tried to place an obsidian into the right slot of an RFTools scanner block and my game crashed

**Comment by Nishh** [comment]
I'm also experiencing the exact same issue.
crash log: https://gist.github.com/Nishh/9ef76b09906af279636c120832f2c27b

**Comment by Shadows-of-Fire** [comment]
Anyone experiencing this issue should attempt to reproduce with this debug jar: https://cdn.discordapp.com/attachments/613013428621017089/1107901925464219741/FastSuite-1.19.2-4.1.0-DEBUG.jar

This will throw an error if a mod tries to mutate an input stack during recipe matching, and then we can work with that mod to not do that.
