### ISSUE TITLE
Understanding blacklisting

### ISSUE THREAD

**Issue by joelra** [Shadows-of-Fire/FastSuite#26]
I apologize that this isn't an actual code issue but is a request for information on how to understand the blacklisting functionality in the config file. I don't know how to contact you other than Github.

My question is how does the blacklist work? The config file references defining a recipe type. Does that mean something like https://minecraft.fandom.com/wiki/Recipe#List_of_recipe_types? Meaning that if I have an issue with crafting a given recipe in a crafting table, I'd have to backlist the entire minecraft:crafting type? Or is there a way to be specific on blacklisting a given tag (e.g. somemodname:sometag)?

**Comment by Shadows-of-Fire** [comment]
You would have to blacklist the entire `minecraft:crafting` type, yes.

If you've discovered a particular crafting recipe that isn't threadsafe, let me know and I'll work their author to resolve it

**Comment by joelra** [comment]
Thank you for the incredibly fast response. The issue I was experiencing was in ATM8 (version 1.0.21b) and trying to craft an XNet Advanced Connector. Working with their discord, it was determined there's an issue with the modpack's version of sophisticated storage and FastSuite. Updating those individual mod versions for sophisticated storage, sophisticated backpacks, and sophisticated core addresses the issue but I was curious as an interim fix until the modpack itself is updated if I could just blacklist a specific tag.

Thanks again for the explanation though. I have my workaround and can use this blacklist for our server until the modpack updates the mod versions.
