### ISSUE TITLE
[1.19.2] Fairy lights incompatibility

### ISSUE THREAD

**Issue by vgrynch** [Shadows-of-Fire/FastSuite#29]
Fairy Lights mod recipes are defined in an unusual way (when the item is returned or used is the same in many recipes, just NBT data is different). A binary search through all mods to find out what causes the issue shows that exactly this mod (Fast Suite) makes Fairy Lights recipes broken.

**Comment by SiverDX** [comment]
Add the custom `types` which have problems from https://github.com/pau101/Fairy-Lights/tree/master/src/generated/resources/data/fairylights/recipes (e.g. `fairylights:crafting_special_copy_color`) to the blacklist, see https://github.com/Shadows-of-Fire/FastSuite/issues/28

**Comment by Shadows-of-Fire** [comment]
That doesn't work for specializations of crafting recipes - the blacklist is for specific recipe types (crafting, smelting, etc).
Fairy lights has been notoriously weird with recipes in the past, as they have special recipes that they do not declare as special recipes.

@vgrynch can you drill down on which particular recipe is broken?

**Comment by vgrynch** [comment]
Actually all recipes related to hanging mini flags on string (do not remember how it is called exactly in the game), and some others, I did not check all.

I will try blacklisting and let you know the result.

**Comment by vgrynch** [comment]
Tried single-threded recipes (blacklistign) option - it did not work. Here is a config I used:
```
# File Specification: https://gist.github.com/Shadows-of-Fire/88ac714a758636c57a52e32ace5474c1

# FastSuite Configuration

general {
    # A list of recipe types which may only be looked up on the main thread. Add a recipe type to this list if errors start happening.
    # Default: [
    S:"Single Threaded Recipe Types" <
       fairylights:crafting_special_triangle_pennant,
       fairylights:crafting_special_color_changing_light,
       fairylights:crafting_special_pennant_bunting,
       fairylights:crafting_special_pennant_bunting_augmentation,
       fairylights:crafting_special_square_pennant,
       fairylights:crafting_special_spearhead_pennant,
       fairylights:crafting_special_swallowtail_pennant,
       fairylights:letter_bunting
     >

    # The max time, in seconds, that a recipe lookup may take before aborting the lookup and logging an error.
    # Default: 25; Range: [1 ~ 300]
    I:"Max Recipe Lookup Time"=25
}
```

**Comment by vgrynch** [comment]
So basically I added all recipes I found related to pennants. Still, none are working, and seems nothing changed in the behavior or in the displaying of recipes by JEI.

**Comment by SiverDX** [comment]
Yeah apparently they're not in the `recipe type` registry
FastSuite might need either `modid` or `recipe serializer registry` blacklist

Don't really know the difference between a recipe type and recipe serializer
But they appear in the `minecraft:recipe_serializer` kubejs dump

```
fairylights:crafting_special_hanging_lights
fairylights:crafting_special_hanging_lights_augmentation
fairylights:crafting_special_tinsel_garland
fairylights:crafting_special_pennant_bunting
fairylights:crafting_special_pennant_bunting_augmentation
fairylights:crafting_special_triangle_pennant
fairylights:crafting_special_spearhead_pennant
fairylights:crafting_special_swallowtail_pennant
fairylights:crafting_special_square_pennant
fairylights:crafting_special_fairy_light
fairylights:crafting_special_paper_lantern
fairylights:crafting_special_orb_lantern
fairylights:crafting_special_flower_light
fairylights:crafting_special_candle_lantern_light
fairylights:crafting_special_oil_lantern_light
fairylights:crafting_special_jack_o_lantern
fairylights:crafting_special_skull_light
fairylights:crafting_special_ghost_light
fairylights:crafting_special_spider_light
fairylights:crafting_special_witch_light
fairylights:crafting_special_snowflake_light
fairylights:crafting_special_heart_light
fairylights:crafting_special_moon_light
fairylights:crafting_special_star_light
fairylights:crafting_special_icicle_lights
fairylights:crafting_special_meteor_light
fairylights:crafting_special_light_twinkle
fairylights:crafting_special_color_changing_light
fairylights:crafting_special_edit_color
fairylights:crafting_special_copy_color
```

**Comment by LiskoSlayer63** [comment]
Tested it some more with different versions and this bug does **not** occur with FastSuite 4.0.0


> FastSuite might need either modid or recipe serializer registry blacklist

This would be the ultimate solution in my opinion too

**Comment by Shadows-of-Fire** [comment]
Fairy Lights' recipe implementation is beyond the most haunted thing I have ever seen, there is pretty much no way to support this.
