### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by lonevox** [Shadows-of-Fire/FastSuite#33]
Could this be uploaded to Modrinth? It is one of the only mods in my pack that isn't on Modrinth so an upload there would be awesome! If a Modrinth release isn't planned, is it okay to distribute your jars in my pack (the actual jar file, not a link)?

**Comment by Shadows-of-Fire** [comment]
No, modrinth is a dying platform at this point.

**Comment by lonevox** [comment]
All good. Is there a reason you believe it's a dying platform? Google trends says modrinth is growing in comparison to curseforge (also keep in mind that curseforge is not only used for Minecraft mods).
![image](https://github.com/Shadows-of-Fire/FastSuite/assets/38600896/15c64fc4-6b73-400c-aefd-faf601c6f8c7)
