### ISSUE TITLE
Crafting Black Stained Glass eventually crashes

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/FastSuite#4]
Relayed from: https://github.com/NillerMedDild/CreateTogether/issues/13

Using `FastSuite-1.16.4-1.0.2`

> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> when me or my friend tries to craft black stained glass the server crashes
> when I spawn it in with /give no problem just the crafting itself is broken.
> 
> **Logs**
> Input pastebin link to crash-report or `latest.log`, if applicable.
> https://pastebin.com/jnNpjF0k

**Comment by Shadows-of-Fire** [comment]
And that stops happening without FS?  Stack doesnt look mod related, it just goes into matches() and stalls, which it still calls with or without FS

**Comment by NielsPilgaard** [comment]
I'll double check, just a sec :)

**Comment by NielsPilgaard** [comment]
Yep it works just fine without FastSuite.

**Comment by Shadows-of-Fire** [comment]
Check if this still occurs with 1.1.0, it was resolving quite a bit of weirdness so it may just fix this.  I was never able to really reproduce this myself.
