### ISSUE TITLE
Mana and Artifice Manaweaving altar doesent work with FastSuite installed

### ISSUE THREAD

**Issue by sirben99** [Shadows-of-Fire/FastSuite#6]
Hey!

I noticed that when FastSuite is installed Manaweaving altar crafting doesent work at all.

Minecraft: 1.16.5
Launcher: MultiMc
Forge: 36.1.32
Mana and Artifice: 1.3.0.6
FastSuite: 1.16.4-1.0.2
Curious: 1.16.5-4.0.5.1
Geckolib: 1.16.5-3.0.41
Placebo: 1.16.4-3.5.0

Latest.log:
[latest.log](https://github.com/Shadows-of-Fire/FastSuite/files/6711129/latest.log)

Debug.log:
[debug.log](https://github.com/Shadows-of-Fire/FastSuite/files/6711131/debug.log)

Steps:
1. Install Mana and Artifice and FastSuite
2. Create a new world in creative
3. In the creative tab, take these items: **Manaweaving Wand, Codex Arcana, stack of Bone Ash, Manaweaving Altar and a stack of Rotten Flesh**
4. Right click ur Codex Arcana, you should hear a music cue, time turned to night and a mana bar in the top left (Or somewhere in ur screen) with a number 1 in the white pentagon
5. Place down Manaweaving Altar
6. In the altar by right clicking place: **6 Rotten Flesh and 1 Bone Ash**. You should see the items floating there
7. Using the Manaweaving Wand, hold right click and draw a circle, it should be placed in the left most square

What should have happened: The ritual should start and the rotten flesh should turn into 3 leather
What happened instead: The ritual doesent start at all.

Im not sure if anything else is broken in this mod because of FastSuite, but Manaweaving Altar is one of them.

Hope this is enough info!

Ben

**Comment by Shadows-of-Fire** [comment]
Closed source mods are not supported (you'll have to have them fix it)

**Comment by sirben99** [comment]
Hey!

I got an response from Mana and Artifice dev:

"Hey there,

In looking at the fastsuite dev's comment, they don't provide any actual information on how to fix the conflict. Since they're the one modifying core forge functionality it falls to them to provide details. My recipes work just fine without fastsuite so it stands to reason that their mod may not play nice with custom recipes.

If they provide some actual context or details on what's needed, or even an attempt to work on it, I'd be happy to work towards compatibility. But the instant close just because M&A isn't open source doesn't give me much hope.

I'm going to close this for now, if you get more details feel free to comment and I'll look into it."

It seems like you should contact Mana and Artifice dev ur self and sort this out.

Ben

**Comment by Shadows-of-Fire** [comment]
I can't really provide any context for what's happening.  All FS really does is reorder the recipes, and without accszs to MAA's internals I can't tell why that would be an issue.

**Comment by sirben99** [comment]
Yeah, i have no idea whats conflicting and why, i still sugsect contacting the dev ur self and sort the conflict out, since i cant do anything in this situation. This is up to u ofc, but maxium conpability should be a big priority imo, whenever possible.

Ben
